language: go
sudo: false
go:
  - 1.2.2
  - 1.3.3
  - 1.4.3
  - 1.5.3
  - 1.6
  - tip
before_install:
script:
  - go test -tags 'noasm'
  - go test -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - go test -run=$^ -bench=.
notifications:
  email:
    recipients:
      - Kunde21@users.noreply.github.com
    on_success: change
    on_failure: always
