language: go
sudo: false
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.5.3
  - tip
before_install:
  - pip install --user codecov
script:
  - go test
after_success:
  - codecov
notifications:
  email:
    recipients:
      - Kunde21@users.noreply.github.com
    on_success: change
    on_failure: always
