language: go
sudo: false
go:
  - 1.5.4
  - 1.6.2
  - tip
before_install:
script:
  - go test ./internal
  - go test ./internal -tags noasm
  - go test -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - go test -run=$^ -bench=.
notifications:
  email:
    recipients:
      - Kunde21@users.noreply.github.com
    on_success: change
    on_failure: always
