language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.5.2
  - tip
script:
  - go test
notifications:
  email:
    recipients:
      - Kunde21@users.noreply.github.com
    on_success: change
    on_failure: always
